### ISSUE TITLE
Add support for using settings.xml as part of the download process

### ISSUE THREAD

**Issue by sshikov** [takari/maven-wrapper#16]
C:\workspace\Courier\7.18>mvn -N io.takari:maven:wrapper
[INFO] Scanning for projects...
[INFO]
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building courier 7.18
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven:0.3.3:wrapper (default-cli) @ courier ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.334 s
[INFO] Finished at: 2015-11-25T16:33:56+03:00
[INFO] Final Memory: 17M/981M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.takari:maven:0.3.3:wrapper (default-cli) on project courier: Error installing the maven-wrapper archive. Cannot dete
rmine the type of archive C:\Users\xxx.m2\repository\io\takari\maven-wrapper\0.1.4\maven-wrapper-0.1.4.tar.gz. Input is not in the .gz format ->

C:\Users\xxx.m2\repository\io\takari\maven-wrapper\0.1.4\maven-wrapper-0.1.4.tar.gz

This is not my local repository. It was redefined in ~/.m2/settings.xml.

**Comment by sshikov** [comment]
I.e., I mean that wrapper downloader should use settings.xml to define proxy and/or mirror repository. This is a must requirement for enterprise with local Nexus setup. And I'm not sure this is always possible to download maven itself, even using this proxy settings.

**Comment by therevoman** [comment]
I also experienced this problem.  It would be nice if the wrapper would look for a system proxy if it can't use settings.xml

I was able to use my system proxy by passing 2 additional system args
`
mvn -e -X -N io.takari:maven:wrapper -Dmaven=3.1.1 -Dhttp.proxyHost=localhost -Dhttp.proxyPort=3128
`
These are defined here: [http://docs.oracle.com/javase/1.5.0/docs/guide/net/proxies.html]

**Comment by vaskrist** [comment]
I second that.

If you are in a corporate environment where the build machine cannot go out to fetch stuff in the internet, but has a perfectly fine working Nexus proxy defined in ~/.m2/settings.xml the wrapper is unusable.

I know I could set the distributionUrl in mavenwrapper.properties to that Nexus, but when the developers use a different Nexus from the build machines for geographical reasons I am at a dead end again.

**Comment by dapperdanman** [comment]
I ran into the same issue today. We are in a corporate environment with an internal Nexus repository that proxies central. The wrapper doesn't work at all.

**Comment by mosabua** [comment]
You can config the download URL of maven in maven.properties file to point at your repo manager.

**Comment by mosabua** [comment]
We do not want to pull in the heavy load of understanding the settings.xml format.

**Comment by sshikov** [comment]
I've not asked about repo manager URL. If you read original message, you can find that as issue was related to proxy and local repository location (also specified in settings.xml). We can have no repo manager, but still need a proxy to access sites out of comporation intranet. 

So, in general this is just one part of solution.

**Comment by mosabua** [comment]
You can now also specify the URL for the wrapper jar or even just rely on it being downloaded or potentially compiled. In any case though.. if you are serious about using Maven in an organization you will need a repository manager and we will also NOT add support for reading the settings.xml. System level proxies might already work .. feel free to test and send a PR for that.

**Comment by adrianshum** [comment]
Just tried Maven Wrapper in environment with restricted internet access.  The limitation is actually quite painful.

Instead of making the wrapper aware of settings.xml, I have another alternative idea:

Similar to distributionUrl, can we provide ability to define base url for download?

Now we have 3 things that will be downloaded by the wrapper:

1. wrapper script downloading Maven dist (can be overridden by distributionUrl, which is stored in .mvn/wrapper/maven-wrapper.properties)
2. Plugin downloading the wrapper tarball.  Now hardcoded to download from repo1.maven.org, and hardcoded to download to $HOME/.m2/repository (personally I would rather just download to tmp dir, as not everyone store the local repo in home, e.g. in build server)
3. mwnw downloading the wrapper jar if missing (which is now hardcoded in mvnw.bat and mvnw shell script, and MavenWrapperDownloader.java

Given in most enterprise environments, there is a centralized repository manager.  If we can have all the above 3 smart enough to download from that centralized repository manager, it will be good enough.

So could we allow the plugin (and the maven-wrapper.properties) to define

1. `downloadBaseUrl`  (which is something like  `http://my.internal/repo` , default = `http://repo1.maven.org/maven2` )
2. `distributionUrl` (work just like now.  However, if it is not defined, we can derive from `$downloadBaseUrl`)
3. `wrapperDownloadUrl` (similar to `$distributionUrl`, which control the download of wrapper tarball.  If not defined, derive from `$downloadBaseUrl`)
4. `wrapperJarDownloadUrl` (similar to `$distributionUrl`, which control download of wrapper JAR.  If not defined, derive from `$downloadBaseUrl` )

With all these, the plugin could work like:

    mvn -N io.takari:maven:wrapper -DdownloadBaseUrl=http://my.internal/repo
    (all 3 downloads will go to `http://my.internal/repo`)

    mvn -N io.takari:maven:wrapper -DdownloadBaseUrl=http://my.internal/repo -DdistributionUrl=http://another.repo/maven.zip
    (wrapper tarball and jar downloads will go through `http://my.internal/repo`, while maven distribution zip will be downloaded from another repo)


I am pleased to implement this if it is agreed to be a acceptable approach.

**Comment by Ebsan** [comment]
Has anyone found a workaround to this? We have an internal nexus repo and mvnw will not work with it.
