### ISSUE TITLE
What about a default settings.xml?

### ISSUE THREAD

**Issue by Randgalt** [takari/maven-wrapper#4]
In a corporate environment, it would be nice to have a default settings.xml. It could be put at <code>.mvn/wrapper/settings.xml</code> and the mvnw script would install it if the user doesn't have a settings.xml. Thoughts?

**Comment by ifedorenko** [comment]
What kind of information do you expect to put in such default settings.xml? 

You can't put user credentials there, as these are user-specific, not project specific. You don't want `<mirrorOf>` or `<proxy>` either, because these are specific to build system and will likely be different between developer and CI. But everything else you should already be able to specify in pom.xml.

**Comment by spencergibb** [comment]
As @jvanzyl mentioned https://github.com/takari/maven-wrapper/issues/3#issuecomment-121678835 you can add maven cmd line options here: `${maven.projectBasedir}/.mvn/maven.config`.  I think we're planning on using it specifically for settings.xml.

**Comment by Randgalt** [comment]
For example, at our company we have a company-wide Nexus. It doesn't need credentials. So, it would be nice to set up the settings.xml with this. Of course, I could just write a script to do this as well.

**Comment by dsyer** [comment]
Repository locations are really my biggest headache (or at least the biggest one that can be solved with `settings.xml`). Those will go straight in `.mvn/maven.config` if I can figure out a way to make settings cumulative (i.e. I don't want to switch off the user's own default `settings.xml`).

**Comment by dsyer** [comment]
As far as I can see there is no way to add `settings.xml` using the wrapper, or normal Maven 3.3 features. If I put `-s .settings.xml` in `.mvn/maven.config` then it will get resolved relative to the user's current working directory, which is wrong if I am building a sub-module. Actually the wrapper doesn't work in a sub-module anyway:

```
$ ../mvnw install -X
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
```

(I'll open another issue for that.)

Here is a realated issue: [MNG-5790](https://issues.apache.org/jira/browse/MNG-5790) where Jason says it is not a problem (or rather suggests that it requires another feature request, which seems to me to be dodging the issue).

Merging settings from different sources is another question. Need to investigate how that works.

**Comment by ifedorenko** [comment]
@dsyer why do you want to specify repository location in `settings.xml` and not `pom.xml`? If project needs specific repository during the build, consumers of project artifacts will almost certainly need the same repositories during their builds. This makes `pom.xml` far better place for repository location or did I misunderstand your usecase?

**Comment by Randgalt** [comment]
@ifedorenko - See here: http://blog.sonatype.com/2009/02/why-putting-repositories-in-your-poms-is-a-bad-idea/

**Comment by dsyer** [comment]
What he said. Using the pom for repository declarations is fine for apps, but not for libraries that are consumed by others.

**Comment by dsyer** [comment]
Opened a new issue here: https://issues.apache.org/jira/browse/MNG-5859. Since maven.config is processed in Maven, not in the wrapper this is the only way it can be fixed for that mechanism.

I'm quite tempted to edit the `mvnw` script anyway and add some default settings. Any down side in that? I guess I can't easily upgrade the wrapper.

**Comment by Randgalt** [comment]
That's what I was going to do. We'd just have a corporate mvnw. The downside is merging future changes.

**Comment by ifedorenko** [comment]
@Randgalt @dsyer mirrorOf=\* proved to cause maintenance problems in the long run, I believe it was a mistake we introduced and promoted it. I stopped using it for my opensource work long time ago and we are phasing out its use in our rather large corporate environment too. will can elaborate if you are interested, but takari users google group is probably a better place.

**Comment by dsyer** [comment]
That sounds like a resounding non-recommendation of something that I never heard of, so that's useful. I googled "takari google group" and got nothing. Do you have a link?

**Comment by ifedorenko** [comment]
https://groups.google.com/forum/?hl=en#!forum/takari-team-user

**Comment by Randgalt** [comment]
I'm going to close this as there are workarounds.

**Comment by dsyer** [comment]
Sorry, I must have missed something. What were the workarounds?

**Comment by Randgalt** [comment]
For me, I added a few lines to mvnw.sh, but if you want I can reopen this. There's also the maven.config workaround mentioned above.

**Comment by dsyer** [comment]
Yeah that didn't work for some things in settings.xml (in particular server authentication). It always replaces what the user has instead of merging with it.

**Comment by nodje** [comment]
Not much progress since Jul 23 it seems.
https://issues.apache.org/jira/browse/MNG-5859 hasn't move a finger (this can take years)
Seems that not even all people in this thread are watching the issue.

@dsyer have you given up on including `mvnw` in your products for now or are you working on another solution already?

What are we left with: manually editing the `mvnw` script is probably the best option for a "corporate" Maven Wrapper for now, right?

**Comment by dsyer** [comment]
Yeah, I use my own version of the wrapper. It would be nice if something would work out of the box though.

**Comment by jvanzyl** [comment]
For the use of a settings.xml using the .mvn/maven.config with parameters to a settings.xml file is not working? As @ifedorenko pointed out above most settings are user specific so are you wanting to put repository configurations there? Visa-a-vis filtering the wrapper does not work from a sub-module so have you fixed this in order for you version to work? If so that patch is patch is likely necessary first before filtering any parameters would make sense. If your changes made the execution relative to the project directory, though, than filtering for this use case wouldn't be necessary.

**Comment by nodje** [comment]
Being able to include the `settings.xml` file into a project would be very useful, and that's an issue independent from `mvnw` itself.

If I read correctly, the only thing that prevents using `-s settings.xml` in `maven.config` for that purpose is that it's not possible to specify settings.xml relative to the project directory.
As asked in https://issues.apache.org/jira/browse/MNG-5790, the feature request that would allow this is https://issues.apache.org/jira/browse/MNG-5859. Let's support it.

**Comment by francisoud** [comment]
Got the same problem, here some workarounds...

Basically my use case is: "if someone in corp XXX checkout the source code and launch mvnw it fails because maven central is inaccessible (need proxy configuration)"

The company answer is "just copy/paste the provided settings.xml in your ~/.m2 folder"

I could add an extra line to my README.md saying so but I found 2 solutions:
- Commit settings.xml in the project folder and [add a line](https://gist.github.com/francisoud/135ea9215114f43f49a7bb8e9ac4516a) in mvnw (e.g in mvnw.cmd):

`IF NOT EXIST "%USERPROFILE%\.m2\settings.xml" call xcopy /F %CD%\settings.xml %USERPROFILE%\.m2\
`
- Just as [mentioned above](https://github.com/takari/maven-wrapper/issues/4#issuecomment-121695664): commit settings.xml in the project folder and add a `{projectroot}/.mvn/maven.config` witt the following content:

`-s settings.xml`

Both workarounds have their advantages and drawbacks...
I don't plan on build my project outside of this company so less headaches ahead ;)

**Comment by ajdocherty** [comment]
Adding `.mvn/maven.config` with the `-s` parameter value doesn't work for me when building in docker.

**Comment by yborovikov** [comment]
@Randgalt the issue (with repos and other stuff in the released poms) described in the sonatype blog you mentioned can/should be resolved by applying [`flatten-maven-plugin`](http://www.mojohaus.org/flatten-maven-plugin/).

**Comment by gzm55** [comment]
@Randgalt  [project-settings-extension](https://github.com/gzm55/project-settings-maven-extension#example) fits corporate environment very well, it just loads the __project-level__ settings at .mvn/settings.xml

**Comment by yborovikov** [comment]
Here's a tiny script we use:
```bash
#!/bin/bash
# This script is expected to be run from the repository root directory.

MVNW="./mvnw" # maven wrapper script (relative to the repository root)

if [[ -x "$MVNW" ]]; then # if the repo has an executable maven wrapper installed
    MH=$(mvn --version | awk '/^Maven home: /{print $NF}') # find default maven home
    if [[ -r $MH/conf/settings.xml ]]; then # if default maven home has global settings
        MVN="$MVNW --global-settings $MH/conf/settings.xml" # use maven wrapper with default maven global settings
    else
        MVN="$MVNW" # use maven wrapper
    fi
else
    MVN="mvn" # use default maven command if there is no wrapper installed in the repo
fi

set -x

${MVN} "$@"
```
It will run maven wrapper with global settings from stock maven home (if present) or just use stock maven if there's no wrapper.
