### ISSUE TITLE
explicitly enable http proxies

### ISSUE THREAD

**Issue by grandinj** [takari/maven-wrapper#58]
when building under Linux (in this case Ubuntu Linux) using

    ./mvnw clean verify

from behind a proxy, the maven/java stuff will not use the system proxies unless explicitly told to do so, which is a problem when maven tries to download the jars it needs :-)

please also see original issue here: https://github.com/pmd/pmd/issues/498

I'm guessing you are going to tell me I need to log a bug report against maven itself, but at least this is one step forward :-)

**Comment by mosabua** [comment]
Just set the property in .mvn/jvm.config 

See https://maven.apache.org/docs/3.3.1/release-notes.html

**Comment by mosabua** [comment]
Alternatively I am not sure if you can set a global setting for all Maven invocations somewhere in general or even beyond that for all Maven projects. Automatically enabling the proxy if configured in the wrapper might be okay but I am not sure this is right overall and in line with all other java programs.. so I am weary to go down that road with the wrapper.

**Comment by Bananeweizen** [comment]
Specifying the proxy in the project specific jvm.config is a bad idea for multiple reasons and this issue should be re-opened:
* Freshly checked out repositories with mvnw enabled projects don't have a jvm.config, to begin with. Therefore this must be added to each and every project one is working with, instead of setting it once centrally. This makes it basically impossible to introduce mvnw in corporate environments, where authorized proxies are the norm.
* The jvm.config contains settings which shall be shared by team members (i.e. the file is under version control), as well as my personal password. This concept doesn't work in team environments.
