### ISSUE TITLE
Fails to load maven-wrapper.jar on Windows if there is a space in the path

### ISSUE THREAD

**Issue by theangrydev** [takari/maven-wrapper#92]
For example:
```
C:\Users\Spaces User\Project> .\mvnw clean
'#' is not recognized as an internal or external command,
operable program or batch file.
Error: Could not find or load main class User\Project\.mvn\wrapper\maven-wrapper.jar
```

**Comment by mschaaf** [comment]
This happens also on a Linux build machine for me.

**Comment by mosabua** [comment]
Don't use space in your paths ever. If you insist on using spaces you probably have lots of other tools also breaking. If you want this fixed on the wrapper you would have to create a fix and submit a PR.

**Comment by theangrydev** [comment]
This is the most unhelpful response to an issue I have seen in a while on GitHub. Of course I can recommend to my clients not to use spaces in the path but some will do it anyway or be forced to because of corporate machine restrictions. It is common for Windows tools to support spaces since Windows users are so used to doing it.

**Comment by mosabua** [comment]
I am sorry that this is an issue for you but I do not have the time to implement support for a edge case like this. I am more than happy to look at a PR, review and merge and test it (not on Windows though since I dont have a Windows machine) and then cut a release. That alone is quite a bit of work. So if you corporation needs support for this please get them to invest the development time and effort to create a PR.
